"""change_students_models

Revision ID: f987e075bea9
Revises: 
Create Date: 2016-12-07 08:38:42.219534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f987e075bea9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_students_number', table_name='students')
    op.create_index(op.f('ix_students_number'), 'students', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_number'), table_name='students')
    op.create_index('ix_students_number', 'students', ['number'], unique=False)
    # ### end Alembic commands ###
